version: '3.5'
services:

  site:
    image: rycus86/podlike
    command: -logs
    labels:
      pod.component.app: |
        image: rycus86/demo-site
        environment:
          - HTTP_HOST=0.0.0.0
          - HTTP_PORT=12000
      # add in a proxy component
      pod.component.proxy: |
        image: nginx:1.13.10
        volumes:
          - nginx-config:/etc/nginx/conf.d
        depends_on:
          config-writer:
            condition: service_healthy
      # write the Nginx config from an inline string for demo purposes
      pod.component.config-writer: |
        image: rycus86/write
        volumes:
          - nginx-config:/etc/nginx/conf.d
        environment:
          TARGET: /etc/nginx/conf.d/default.conf
          DATA: |
            proxy_cache_path  /tmp/nginx.cache  levels=1:2  keys_zone=cache:10m inactive=12h max_size=50m;

            server {
                listen       80;
                server_name  localhost;

                # proxy all requests to the app on port 12000
                location / {
                    proxy_pass   http://127.0.0.1:12000;

                    proxy_set_header       Host $$host;
                    proxy_cache            cache;
                    proxy_cache_valid      200 5m;
                    proxy_cache_use_stale  error timeout invalid_header updating
                                           http_500 http_502 http_503 http_504;
                }
            }
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx-config:
