version: '3.5'
services:

  # our legacy calculator application
  calc:
    image: rycus86/podlike
    command: -logs
    configs:
      - source: calc-app
        target: /etc/apps/calculator.py
      - source: calc-conf
        target: /etc/conf/calc-conf.json
    labels:
      # the sample application
      pod.copy.app: /etc/apps/calculator.py:/app-server.py
      pod.component.app: |
        image: python:2.7-alpine
        command: python /app-server.py
      # the reverse proxy
      pod.component.traefik: |
        image: traefik
        command: >
          --consulcatalog --consulcatalog.watch
          --consulcatalog.constraints='tag==calc'
          --consulcatalog.endpoint=127.0.0.1:8500
          --consulcatalog.frontendrule='PathPrefix: /{{.ServiceName}}'
          --tracing.backend=zipkin --tracing.zipkin --tracing.servicename=v1/calc
          --tracing.zipkin.httpendpoint=http://zipkin:9411/api/v1/spans
      # the service discovery agent
      pod.copy.consul-agent: /etc/conf/calc-conf.json:/consul/config/calc.json
      pod.component.consul-agent: |
        image: consul
        command: agent -join=consul -enable-script-checks
        environment:
          CONSUL_BIND_INTERFACE: eth0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # the new service for the add operation
  add:
    image: rycus86/podlike
    command: -logs
    configs:
      - source: add-app
        target: /etc/apps/add.py
      - source: add-conf
        target: /etc/conf/add-conf.json
    labels:
      # the sample application
      pod.copy.app: /etc/apps/add.py:/app-server.py
      pod.component.app: |
        image: python:2.7-alpine
        command: python /app-server.py
      # the reverse proxy
      pod.component.traefik: |
        image: traefik
        command: >
          --consulcatalog --consulcatalog.watch --consulcatalog.prefix=add
          --consulcatalog.constraints='tag==internal'
          --consulcatalog.endpoint=127.0.0.1:8500
          --tracing.backend=zipkin --tracing.zipkin --tracing.servicename=v2/add
          --tracing.zipkin.httpendpoint=http://zipkin:9411/api/v1/spans
      # the service discovery agent
      pod.copy.consul-agent: /etc/conf/add-conf.json:/consul/config/add.json
      pod.component.consul-agent: |
        image: consul
        command: agent -join=consul -enable-script-checks
        environment:
          CONSUL_BIND_INTERFACE: eth0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # the new service for the multiply operation
  mul:
    image: rycus86/podlike
    command: -logs
    configs:
      - source: mul-app
        target: /etc/apps/multiply.py
      - source: mul-conf
        target: /etc/conf/mul-conf.json
    labels:
      # the sample application
      pod.copy.app: /etc/apps/multiply.py:/app-server.py
      pod.component.app: |
        image: python:2.7-alpine
        command: python /app-server.py
      # the reverse proxy
      pod.component.traefik: |
        image: traefik
        command: >
          --consulcatalog --consulcatalog.watch --consulcatalog.prefix=mul
          --consulcatalog.constraints='tag==internal'
          --consulcatalog.endpoint=127.0.0.1:8500
          --tracing.backend=zipkin --tracing.zipkin --tracing.servicename=v2/mul
          --tracing.zipkin.httpendpoint=http://zipkin:9411/api/v1/spans
      # the service discovery agent
      pod.copy.consul-agent: /etc/conf/mul-conf.json:/consul/config/mul.json
      pod.component.consul-agent: |
        image: consul
        command: agent -join=consul -enable-script-checks
        environment:
          CONSUL_BIND_INTERFACE: eth0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # reverse proxy for external requests
  router:
    image: traefik
    command: >
      --api --api.dashboard --metrics.prometheus
      --tracing.backend=zipkin --tracing.zipkin --tracing.servicename=router
      --tracing.zipkin.httpendpoint=http://zipkin:9411/api/v1/spans
      --consulcatalog --consulcatalog.watch
      --consulcatalog.constraints='tag==external'
      --consulcatalog.endpoint=consul:8500
      --consulcatalog.frontendrule='PathPrefix: /{{.ServiceName}}'
    ports:
      - 8080:8080
      - 80:80

  # the main Consul server
  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: eth1
    ports:
      - 8500:8500

  # request trace collector
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      STORAGE_TYPE: mem

configs:
  calc-app:
    file: ./calc/calculator-server.py
  calc-conf:
    file: ./calc/consul-config.json
  add-app:
    file: ./add/add-server.py
  add-conf:
    file: ./add/consul-config.json
  mul-app:
    file: ./mul/multiply-server.py
  mul-conf:
    file: ./mul/consul-config.json
